#!/usr/bin/env zsh

__import "print/print"

local arg opt

arg="${1:?}"
opt="__${arg##*-}__"
shift

case "$arg" in
    "-")
        # TODO
        ;;

    "--")
        # TODO
        ;;

    *)
        if [[ -f $ZPLUG_ROOT/autoload/options/$opt ]]; then
            # call option file if exists
            $opt "$@"

        else
            __zplug::print::print::die \
                "[zplug] $arg: no such option\n"
            return 1
        fi
        ;;
esac
