#!/bin/zsh

__import "print/print"

local    arg key
local -a parsed_zplugs
local -A zplugs_tags
local    name as of from if dir file at do frozen on commit nice ignore

if [[ -z $1 ]]; then
    __die "$funcstack[1]: too few arguments\n"
    return 1
fi
arg="$1"
arg="${arg}, ${zplugs[$arg]%, }"
parsed_zplugs=(${(s/, /)arg:gs/,  */, })

name="${parsed_zplugs[1]}"
as=${${${(M)parsed_zplugs:#as:*}#*:}:-plugin}
of=${${${(M)parsed_zplugs:#of:*}#*:}:--EMP-}
from=${${${(M)parsed_zplugs:#from:*}#*:}:-github}
if=${${${(M)parsed_zplugs:#if:*}#*:}:--EMP-}
dir=${${${(M)parsed_zplugs:#dir:*}#*:}:--EMP-}
file=${${${(M)parsed_zplugs:#file:*}#*:}:--EMP-}
at=${${${(M)parsed_zplugs:#at:*}#*:}:-master}
do=${${${(M)parsed_zplugs:#do:*}#*:}:--EMP-}
frozen=${${${(M)parsed_zplugs:#frozen:*}#*:}:-0}
on=${${${(M)parsed_zplugs:#on:*}#*:}:--EMP-}
commit=${${${(M)parsed_zplugs:#commit:*}#*:}:--EMP-}
nice=${${${(M)parsed_zplugs:#nice:*}#*:}:-0}
ignore=${${${(M)parsed_zplugs:#ignore:*}#*:}:--EMP-}

if [[ $name == $_ZPLUG_OHMYZSH ]] && [[ $nice -eq 0 ]]; then
    nice=-10
fi

zplugs_tags=(
name    "$name"
as      "$as"
of      "$of"
from    "$from"
if      "$if"
dir     "$dir"
file    "$file"
at      "$at"
do      "$do"
frozen  "$frozen"
on      "$on"
commit  "$commit"
nice    "$nice"
ignore  "$ignore"
)

# Output zplugs_tags
# Separated by newline
# because it is used by parameter expansion flags (@f)
for key in ${(k)zplugs_tags}
do
    __put "${key}\n${zplugs_tags[$key]}\n"
done
