#!/usr/bin/env zsh

__import "core/core"
__import "print/print"

local    arg="$1" tag
local -a tags

if [[ -z $arg ]]; then
    __zplug::print::print::die "[zplug] $funcstack[1]: too few arguments\n"
    return 1
fi

__zplug::core::core::get_tags
tags=( "${reply[@]}" )

reply=("name" "$arg")
for tag in "${tags[@]}"
do
    reply+=("$tag" "$(__${tag}__ "$arg")")
done
