#!/bin/zsh

__import "core/core"
__import "print/print"

local main
main="b4b4r07/zplug"

__put "$fg_bold[default] * zplug self management$reset_color\n"

if __check__ "$main"; then
    __update__ "$main"
else
    if ! __zpluged "$main"; then
        __add__ "$main"
    fi
    ZPLUG_SHALLOW=false __install__ "$main"
fi

ln -snf \
    "$ZPLUG_HOME/repos/$main/init.zsh" \
    "$ZPLUG_HOME/init.zsh"

if (( $status == 0)) && [[ -d $ZPLUG_HOME/repos/$main ]]; then
    __put "$fg[green]Everything is ready. "
    __put "$fg_bold[default]($ZPLUG_HOME/zplug)$reset_color\n"
else
    __die "$fg[red]Error occured (see ${(%):-"%U"}$_ZPLUG_URL${(%):-"%u"})$reset_color\n"
    return 1
fi
