#!/usr/bin/env zsh
# Description:
#   Commands to run after loading

local    arg="$1" package
local -a parsed_zplugs
local    hook_load
local    default=""

package="${arg}, ${zplugs[$arg]%, }"
parsed_zplugs=(${(s/, /)package/,  */, })

hook_load="${parsed_zplugs[(k)hook-load:*]#hook-load:*}"
if [[ -z $hook_load ]]; then
    zstyle -s ":zplug:tag" hook-load hook_load
fi

echo "${hook_load:-$default}"
