#!/usr/bin/env zsh
# Description:
#   rename-to tag

local    arg="$1" package
local -a parsed_zplugs
local    rename_to
local    default=""

if [[ -n $arg ]] && ! __zplug::base::base::zpluged "$arg"; then
    __zplug::io::log::error \
        "$arg: no package managed by zplug"
    return 1
fi

package="${arg}, ${zplugs[$arg]%, }"
parsed_zplugs=(${(s/, /)package/,  */, })

rename_to="${parsed_zplugs[(k)rename-to:*]#rename-to:*}"
if [[ -z $rename_to ]]; then
    zstyle -s ":zplug:tag" rename-to rename_to
fi

echo "${rename_to:-$default}"
