#!/usr/bin/env zsh

__import "core/core"
__import "print/print"

local    arg="$1" package
local -a parsed_zplugs
local    use
local    default="*.zsh"

package="${arg}, ${zplugs[$arg]%, }"
parsed_zplugs=(${(s/, /)package/,  */, })

use="${parsed_zplugs[(k)use:*]#use:*}"
if [[ -z $use ]]; then
    zstyle -s ":zplug:tag" use use
fi

echo "${use:-$default}"
