'\" t
.\"     Title: zplug-update
.\"    Author: [see the "Authors" section]
.\" Generator: DocBook XSL Stylesheets v1.75.2 <http://docbook.sf.net/>
.\"      Date: 05/04/2016
.\"    Manual: ZPLUG Manual
.\"    Source: ZPLUG Manual
.\"  Language: English
.\"
.TH "ZPLUG\-UPDATE" "1" "05/04/2016" "ZPLUG Manual" "ZPLUG Manual"
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
zplug-update \- Update installed packages in parallel
.SH "SYNOPSIS"
.sp
.nf
\fIzplug update\fR [\-\-self|\-\-select [\fI"username/reponame"\fR]]
.fi
.sp
.nf
The word \'package\' refers to the string in the format: "username/reponame"\&.
.fi
.SH "DESCRIPTION"
.sp
Update installed packages and zplug by itself\&.
.SH "OPTIONS"
.PP
\fB\-\-self\fR
.RS 4
Use this command to update your copy of zplug\&.
.RE
.PP
\fB\-\-select\fR
.RS 4
Choose the package that is not updated from the list and update it\&.
.RE
.SH "EXAMPLES"
.sp
Update:
.sp
.if n \{\
.RS 4
.\}
.nf
$ zplug update
Updating\&.\&.\&.          mollifier/zload
Updating\&.\&.\&.          stedolan/jq
Updating\&.\&.\&.          glidenote/hub\-zsh\-completion
Frozen repo          junegunn/fzf\-bin                 (0\&.42s)
Frozen repo          stedolan/jq                      (0\&.47s)
Up\-to\-date           b4b4r07/http_code                (2\&.29s)
Up\-to\-date           b4b4r07/zsh\-vimode\-visual        (2\&.29s)
Up\-to\-date           b4b4r07/emoji\-cli                (2\&.68s)
Up\-to\-date           mollifier/zload                  (2\&.69s)
Updated!             b4b4r07/ssh\-keyreg               (2\&.84s)
Updated!             zsh\-users/zsh\-completions        (4\&.00s)
.fi
.if n \{\
.RE
.\}
.sp
Update zplug:
.sp
.if n \{\
.RS 4
.\}
.nf
$ zplug update \-\-self
 * zplug self management
Updating\&.\&.\&.          zplug/zplug
Up\-to\-date           zplug/zplug      (2\&.42s)
Everything is ready\&. (~/\&.zplug/zplug)
.fi
.if n \{\
.RE
.\}
.SH "SEE ALSO"
.sp
\fBzplug(1)\fR
.SH "FURTHER DOCUMENTATION"
.sp
See the references in official wiki page to get started using zplug\&. The wiki may perhaps be overwhelming for first\-time users\&.
.SH "AUTHORS"
.sp
zplug was originally written by Masaki Ishi (a\&.k\&.a @b4b4r07)\&. Many people have contributed to it\&.
.SH "COPYING"
.sp
Copyright (C) 2015\-2016 Masaki Ishi
.sp
MIT License
.SH "REPORTING BUGS"
.sp
Report bugs to the zplug issues
