'\" t
.\"     Title: zplug-as
.\"    Author: [see the "Authors" section]
.\" Generator: DocBook XSL Stylesheets v1.75.2 <http://docbook.sf.net/>
.\"      Date: 11/21/2016
.\"    Manual: ZPLUG Manual
.\"    Source: ZPLUG Manual
.\"  Language: English
.\"
.TH "ZPLUG\-AS" "5" "11/21/2016" "ZPLUG Manual" "ZPLUG Manual"
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
zplug-as \- Specify whether to register the package as plugins or commands
.SH "SYNOPSIS"
.sp
.nf
\fIzplug\fR \fI"username/reponame"\fR, \fIas:plugin\fR
.fi
.sp
.nf
The word \'package\' refers to the string in the format: "username/reponame"\&.
.fi
.SH "DESCRIPTION"
.sp
By using as tag, you can choose whether the package you want to install will be installed as the plugin or as the command\&.
.sp
.it 1 an-trap
.nr an-no-space-flag 1
.nr an-break-flag 1
.br
.B Table\ \&1.\ \&zplug as tag
.TS
allbox tab(:);
ltB ltB.
T{
Possive Values
T}:T{
Default value
T}
.T&
lt lt.
T{
.sp
plugin, command, theme
T}:T{
.sp
plugin
T}
.TE
.sp 1
.sp
Besides, by using zstyle command, you can change default value:
.sp
.if n \{\
.RS 4
.\}
.nf
$ zstyle ":zplug:tag" as command
.fi
.if n \{\
.RE
.\}
.SH "EXAMPLES"
.sp
As a plugin:
.sp
.if n \{\
.RS 4
.\}
.nf
$ zplug "b4b4r07/enhancd", \e
    as:plugin, \e
    use:enhancd\&.sh
.fi
.if n \{\
.RE
.\}
.sp
As a command:
.sp
.if n \{\
.RS 4
.\}
.nf
$ zplug "stedolan/jq" \e
    as:command, \e
    from:gh\-r, \e
    use:"*darwin*"
.fi
.if n \{\
.RE
.\}
.sp
As a theme:
.sp
.if n \{\
.RS 4
.\}
.nf
$ zplug \'themes/apple\', \e
    as:theme, \e
    from:oh\-my\-zsh
.fi
.if n \{\
.RE
.\}
.SH "SEE ALSO"
.sp
\fBzplug(1)\fR
.SH "FURTHER DOCUMENTATION"
.sp
See the references in official wiki page to get started using zplug\&. The wiki may perhaps be overwhelming for first\-time users\&.
.SH "AUTHORS"
.sp
zplug was originally written by Masaki Ishiyama (a\&.k\&.a @b4b4r07)\&. Many people have contributed to it\&.
.SH "COPYING"
.sp
Copyright (C) 2015\-2016 Masaki Ishiyama
.sp
MIT License
.SH "REPORTING BUGS"
.sp
Report bugs to the zplug issues
