#!/usr/bin/env zsh

__import "print/print"

local    f  arg
local -a fs args

while (( $# > 0 ))
do
    arg="$1"
    case "$arg" in
        -*|--*)
            break
            ;;
        *)
            fs=( "$(echo $ZPLUG_HOME/doc/man/man(1|5)/(zplug-|)${arg}.(1|5)(N))" )
            # Non-existing man page
            if [[ $fs[1] == "" ]]; then
                __zplug::print::print::die "[zplug] $arg: no such subcommand or tag\n"
                return 1
            fi
            # List all hits pages
            for f in "${fs[@]}"
            do
                if [[ -f $f ]]; then
                    args+=( "$f" )
                fi
            done
            ;;
    esac
    shift
done

if (( $#args > 0 )); then
    man "${args[@]}"
    return $status
fi
__zplug::print::print::die "$_ZPLUG_HELP\n"

return 1
