'\" t
.\"     Title: zplug-install
.\"    Author: [see the "Authors" section]
.\" Generator: DocBook XSL Stylesheets v1.75.2 <http://docbook.sf.net/>
.\"      Date: 11/21/2016
.\"    Manual: ZPLUG Manual
.\"    Source: ZPLUG Manual
.\"  Language: English
.\"
.TH "ZPLUG\-INSTALL" "1" "11/21/2016" "ZPLUG Manual" "ZPLUG Manual"
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
zplug-install \- Install packages in parallel
.SH "SYNOPSIS"
.sp
.nf
\fIzplug install\fR [\fI"username/reponame"\fR]
.fi
.sp
.nf
The word \'package\' refers to the string in the format: "username/reponame"\&.
.fi
.SH "DESCRIPTION"
.sp
Install the package that has not yet been installed, even though it is described in the file\&.
.SH "OPTIONS"
.PP
\fB(None)\fR
.RS 4
no options
.RE
.SH "EXAMPLES"
.sp
Install all not\-installed packages:
.sp
.if n \{\
.RS 4
.\}
.nf
$ zplug install
.fi
.if n \{\
.RE
.\}
.sp
Install a particular package verbosely:
.sp
.if n \{\
.RS 4
.\}
.nf
$ zplug install \'some_author/some_repo\'
Installing\&.\&.\&.        some_author/some_repo
Installed!           some_author/some_repo (2\&.59s)
 ==> Installation finished successfully!
 zplug: total wall\-time 2\&.664253 sec\&.
.fi
.if n \{\
.RE
.\}
.SH "ENVIRONMENT VARIABLES"
.PP
\fIZPLUG_THREADS\fR
.RS 4
The maximum number of threads zplug should use when installing/updating\&. The default value is 16\&.
.RE
.PP
\fIZPLUG_PROTOCOL\fR
.RS 4
Defaults to HTTPS\&. Valid options for
$ZPLUG_PROTOCOL
are
HTTPS
or
SSH\&. Unless you have a specific reason, you should use the HTTPS protocol\&. For more information, see also
Which remote URL should I use? \- GitHub Help
.RE
.SH "SEE ALSO"
.sp
\fBzplug(1)\fR
.SH "FURTHER DOCUMENTATION"
.sp
See the references in official wiki page to get started using zplug\&. The wiki may perhaps be overwhelming for first\-time users\&.
.SH "AUTHORS"
.sp
zplug was originally written by Masaki Ishiyama (a\&.k\&.a @b4b4r07)\&. Many people have contributed to it\&.
.SH "COPYING"
.sp
Copyright (C) 2015\-2016 Masaki Ishiyama
.sp
MIT License
.SH "REPORTING BUGS"
.sp
Report bugs to the zplug issues
