'\" t
.\"     Title: zplug-list
.\"    Author: [see the "Authors" section]
.\" Generator: DocBook XSL Stylesheets v1.75.2 <http://docbook.sf.net/>
.\"      Date: 12/03/2016
.\"    Manual: ZPLUG Manual
.\"    Source: ZPLUG Manual
.\"  Language: English
.\"
.TH "ZPLUG\-LIST" "1" "12/03/2016" "ZPLUG Manual" "ZPLUG Manual"
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
zplug-list \- List installed packages
.SH "SYNOPSIS"
.sp
.nf
\fIzplug list\fR [\-\-select] [\fI"username/reponame"\fR]
.fi
.sp
.nf
The word \'package\' refers to the string in the format: "username/reponame"\&.
.fi
.SH "DESCRIPTION"
.sp
List installed packages\&.
.SH "OPTIONS"
.PP
\fB\-\-select\fR
.RS 4
List package information chosen from the list\&.
.RE
.SH "EXAMPLES"
.sp
List:
.sp
.if n \{\
.RS 4
.\}
.nf
$ zplug list
zplug/zplug  =>  nil
/Users/b4b4r07/\&.modules  =>  from:local, use:*\&.sh
b4b4r07/zsh\-gomi  =>  as:command, use:bin/gomi
glidenote/hub\-zsh\-completion  =>  nil
peco/peco  =>  as:command, from:gh\-r, frozen:1
so\-fancy/diff\-so\-fancy  =>  as:command, use:diff\-so\-fancy
b4b4r07/zgit  =>  as:command, use:bin, on:junegunn/fzf\-bin
~/enhancd  =>  use:init\&.sh, from:local
Jxck/dotfiles  =>  as:command, use:bin/l
mrowa44/emojify  =>  as:command
.fi
.if n \{\
.RE
.\}
.sp
List a particular package:
.sp
.if n \{\
.RS 4
.\}
.nf
$ zplug list \'mrowa44/emojify\'
mrowa44/emojify  =>  as:command
.fi
.if n \{\
.RE
.\}
.SH "SEE ALSO"
.sp
\fBzplug(1)\fR
.SH "FURTHER DOCUMENTATION"
.sp
See the references in official wiki page to get started using zplug\&. The wiki may perhaps be overwhelming for first\-time users\&.
.SH "AUTHORS"
.sp
zplug was originally written by Masaki Ishiyama (a\&.k\&.a @b4b4r07)\&. Many people have contributed to it\&.
.SH "COPYING"
.sp
Copyright (C) 2015\-2016 Masaki Ishiyama
.sp
MIT License
.SH "REPORTING BUGS"
.sp
Report bugs to the zplug issues
